import com.example.model.GamePlay;

rule "Accumulated winAmount < -50"
when
    $gamePlay: GamePlay() from entry-point "GamePlayStream"
    $totalWinAmount: Number(longValue < -50) from accumulate(
        GamePlay($userId: userId, $winAmount: winAmount, userId == $gamePlay.userId) from entry-point "GamePlayStream",
        sum($winAmount)
    )
then
    // Rule logic here
    System.out.println("Total winAmount is " + $totalWinAmount + " Player with this userID: " + $gamePlay.getUserId() + " has accumulated winAmount less than -50");
end
