import com.example.model.GamePlay
import com.example.consumer.Consumer

rule "Detect large winAmount event"
when
    $event1 : GamePlay( winAmount > 5.0 ) over window:length(10) from entry-point "GamePlayStream"
    $event2 : GamePlay( winAmount > 5.0, this after[5, 8] $event1 ) from entry-point "GamePlayStream"
then
    Consumer.LOGGER.info("Rule Fired: Large winAmount event detected for gamePlayId " + $event2.getGamePlayId() );
end